---
before_install:
  - "chmod +x gradlew"
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - openjdk11
language: java
notifications:
  email:
    recipients:
      - alstlr815@gmail.com
script: "./gradlew clean build"

#language: java
#jdk:
#  - openjdk11
#
#branches:
#  only:
#    - master
#
## Travis CI 서브의 HOME
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'
#
#script: "./gradlew clean build"
#
##CI 실행 완료 시 메일로 알람
#  notifications:
#    email:
#      recipients:
#        - alstlr815@gmail.com
#
#
#
