---
before_install:
  - "chmod +x gradlew"
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk:
  - openjdk11
language: java
notifications:
  email:
    recipients:
      - alstlr815@gmail.com
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/fosting.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fosting-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fosting-build
    key: fosting.zip
    bundle_type: zip
    application: fosting
    deployment_group: fosting
    region: ap-northeast-2
    wait-until-deployed: true

#language: java
#jdk:
#  - openjdk11
#
#branches:
#  only:
#    - master
#
## Travis CI 서브의 HOME
#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'
#
#script: "./gradlew clean build"
#
##CI 실행 완료 시 메일로 알람
#  notifications:
#    email:
#      recipients:
#        - alstlr815@gmail.com
#
#
#
